In [1]:
import numpy as np
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [2]:
le = LabelEncoder()

In [3]:
df = pd.read_csv("oversupply_classification_2015_2026.csv")

In [4]:
df

,Year,District,Crop,Predicted_Production_tons,Predicted_Demand_tons,Supply_Demand_Gap_tons,Supply_Demand_Gap_percent,Production_to_Demand_Ratio,Production_Growth_percent,Demand_Growth_percent,Avg_Mandi_Price_Current,Price_Change_percent,Mandi_Arrival_Growth_percent,Buffer_Stock_Level_tons,Oversupply_Risk_Level
0,2015,Barmer,Pearl Millet,209856.70,160016.86,49839.84,31.15,1.3115,-0.30,-0.54,3709.41,3.68,21.23,5260.00,2
1,2015,Barmer,Finger Millet,155480.45,118926.78,36553.67,30.74,1.3074,-1.88,5.11,1579.61,-13.04,12.75,27702.13,2
2,2015,Barmer,Sorghum,105110.16,109801.52,-4691.36,-4.27,0.9573,14.66,-4.87,3917.46,4.43,1.91,8618.50,0
3,2015,Barmer,Foxtail Millet,289303.27,265666.40,23636.87,8.90,1.0890,-5.40,-3.07,4042.48,1.13,18.25,36756.86,1
4,2015,Barmer,Kodo Millet,184057.02,227597.16,-43540.14,-19.13,0.8087,2.60,6.04,3988.21,1.65,20.16,29290.26,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3835,2026,Etawah,Foxtail Millet,167755.51,133772.67,33982.84,25.40,1.2540,-1.88,-2.80,2062.81,-3.84,2.74,32585.78,2
3836,2026,Etawah,Kodo Millet,201856.84,181428.51,20428.33,11.26,1.1126,10.82,9.00,4398.10,11.82,-1.30,21150.07,1
3837,2026,Etawah,Barnyard Millet,196153.63,147996.10,48157.52,32.54,1.3254,17.67,5.10,4437.63,-2.88,-7.69,3198.64,2
3838,2026,Etawah,Little Millet,280740.48,267329.85,13410.63,5.02,1.0502,9.95,-2.62,1589.89,-5.04,-8.57,2754.82,1


In [5]:
df['Crop'] = le.fit_transform(df['Crop'])


df = df.drop('Year', axis=1)

df = df.drop('District', axis=1)

In [6]:

X = df.drop("Oversupply_Risk_Level", axis=1)
y = df["Oversupply_Risk_Level"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42,
    eval_metric='logloss'
)

In [12]:
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [13]:
y_pred = model.predict(X_test)

In [14]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.99609375

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       459
           1       1.00      0.97      0.99       118
           2       0.99      1.00      0.99       191

    accuracy                           1.00       768
   macro avg       1.00      0.99      0.99       768
weighted avg       1.00      1.00      1.00       768


Confusion Matrix:
 [[459   0   0]
 [  1 115   2]
 [  0   0 191]]
